# Generated by Django 2.2.10 on 2020-03-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_find',
            name='Faculty',
        ),
        migrations.AddField(
            model_name='school_find',
            name='employee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school_find',
            name='schoolteacher',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
