# Generated by Django 2.2.10 on 2020-03-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_school_find_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantinePPl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num', models.IntegerField()),
                ('inPpl', models.IntegerField()),
                ('outPpl', models.IntegerField()),
                ('toHos', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Chinese_student_Admin',
        ),
        migrations.DeleteModel(
            name='Info_Admin',
        ),
    ]
